name: Run Subs Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC 0点运行

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run subs-check
        uses: beck-8/subs-check@v1  # 关键修改点
        with:
          config: config.yaml
          urls: ${{ secrets.SUB_URL_1 }} ${{ secrets.SUB_URL_2 }} ${{ secrets.SUB_URL_3 }} ${{ secrets.SUB_URL_4 }} ${{ secrets.SUB_URL_5 }} ${{ secrets.SUB_URL_6 }} ${{ secrets.SUB_URL_7 }} ${{ secrets.SUB_URL_8 }} ${{ secrets.SUB_URL_9 }} ${{ secrets.SUB_URL_10 }}
          combine: true
          
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: subs_checked
          path: ./output
